### ISSUE TITLE
Warning: Illegal offset type in isset or empty 

### ISSUE THREAD

**Issue by davideprevosto** [smarteist/sage-woocommerce#1]
Unfortunately I am getting this warning:

`Warning: Illegal offset type in isset or empty  in /app/wp-content/themes/my-sage-theme-name/vendor/illuminate/view/FileViewFinder.php on line 71`

**Comment by smarteist** [comment]
I didn't get it, its a warning or error? and please send me more details and stack trace please.

**Comment by surajkhanal** [comment]
I am also getting this warning.

`Warning: Illegal offset type in isset or empty in D:\xampp\htdocs\wptest\wp-content\themes\mytheme\vendor\illuminate\view\FileViewFinder.php on line 71`

WP Version: 5.6
Theme: Sage 10 master
PHP Version: 7.4.6

**Comment by smarteist** [comment]
> I am also getting this warning.
> 
> `Warning: Illegal offset type in isset or empty in D:\xampp\htdocs\wptest\wp-content\themes\mytheme\vendor\illuminate\view\FileViewFinder.php on line 71`
> 
> WP Version: 5.6
> Theme: Sage 10 master
> PHP Version: 7.4.6

Please copy your stack trace here, i can't help you with error title .

**Comment by smarteist** [comment]
> I am also getting this warning.
> 
> `Warning: Illegal offset type in isset or empty in D:\xampp\htdocs\wptest\wp-content\themes\mytheme\vendor\illuminate\view\FileViewFinder.php on line 71`
> 
> WP Version: 5.6
> Theme: Sage 10 master
> PHP Version: 7.4.6



> Unfortunately I am getting this warning:
> 
> `Warning: Illegal offset type in isset or empty in /app/wp-content/themes/my-sage-theme-name/vendor/illuminate/view/FileViewFinder.php on line 71`

@surajkhanal @davideprevosto
Updated please test the new version, also change view renderer abstract to ```sage.woocommerce.view``` and tell me the result.

**Comment by MehwishUmer** [comment]
Any Solution
