### ISSUE TITLE
Overriding templates in WooCommerce plugins

### ISSUE THREAD

**Issue by mattsims** [smarteist/sage-woocommerce#3]
This doesn't appear to work for overriding templates in WooCommerce plugins, only those in WooCommerce core.  I believe I've identified the issue, so will fix and update PR 👍

**Comment by smarteist** [comment]
@mattsims Update and confirm the bug fix, then u can close this issue.

**Comment by mattsims** [comment]
Looks good!  Thanks for merging so promptly 👍
