### ISSUE TITLE
Undefined function with acorn command

### ISSUE THREAD

**Issue by aitormendez** [smarteist/sage-woocommerce#5]
### Steps to reproduce:

Themes directory:

```
git clone --depth=1 git@github.com:roots/sage.git fb &&  cd fb && rm -rf .git
Yarn && yarn build
```

Activate theme in WP editor.

In trellis directory:

```
Vagrant ssh
cd /srv/www/my-site/current/
wp acorn package:discover
wp acorn vendor:publish --tag="woocommerce"
```

Then, I get:

```
In VendorPublishCommand.php line 277:
Call to undefined function Illuminate\Foundation\Console\base_path() 
```

![Captura de pantalla 2021-06-08 a las 8 42 59](https://user-images.githubusercontent.com/2788577/121136469-fbe76580-c835-11eb-9cf7-958fa49e1fd9.png)

Also, when I add:

```
/*
 * Package Service Providers...
 */
Hexbit\Woocommerce\Providers\WooCommerceServiceProvider::class,
```

Then, I can't publish anything with acorn command. It returns "Call to undefined function" error, even in another packages like poet.

**Comment by smarteist** [comment]
Have you installed PHP packages? It seems you did not run the ```composer install``` command. The package mentioned in the Vendor directory does not exist.

**Comment by fowlercraig** [comment]
I'm also getting this error, after completing `composer install`

**Comment by aitormendez** [comment]
Yes, i did `composer install`.

**Comment by aitormendez** [comment]
Yes, i did `composer instal` from theme directory.

**Comment by tombroucke** [comment]
See https://github.com/roots/acorn/issues/115
